/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006a63",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#31312c",
        "on-background": "#1c1c18",
        "primary-fixed": "#9cf2e8",
        "inverse-on-surface": "#f3f0ea",
        "surface-variant": "#e5e2db",
        "on-primary-fixed-variant": "#00504a",
        "secondary-fixed": "#ffdf9b",
        "outline": "#6e7977",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffe4e4",
        "surface-container-high": "#ebe8e1",
        "surface-container-low": "#f6f3ec",
        "on-surface-variant": "#3e4947",
        "on-tertiary-fixed": "#40000c",
        "surface-container-highest": "#e5e2db",
        "primary-fixed-dim": "#80d5cb",
        "on-error-container": "#93000a",
        "tertiary": "#a6002f",
        "tertiary-fixed": "#ffdada",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-tertiary-fixed-variant": "#920028",
        "on-primary-container": "#a3faef",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e3c37d",
        "on-secondary-fixed": "#251a00",
        "secondary-container": "#fddc94",
        "primary": "#005c55",
        "on-surface": "#1c1c18",
        "error": "#ba1a1a",
        "primary-container": "#0f766e",
        "secondary": "#735b20",
        "surface-container": "#f0eee7",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00201d",
        "on-secondary-container": "#785f24",
        "inverse-primary": "#80d5cb",
        "outline-variant": "#bdc9c6",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface": "#fcf9f2",
        "surface-bright": "#fcf9f2",
        "on-secondary-fixed-variant": "#594409",
        "tertiary-container": "#d2093f",
        "background": "#fcf9f2",
        "surface-dim": "#dcdad3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.5rem"
      },
      spacing: {
        "gutter": "1.5rem",
        "container-padding": "2rem",
        "stack-sm": "1rem",
        "stack-md": "2rem",
        "unit": "8px",
        "stack-lg": "4rem"
      },
      fontFamily: {
        "headline-md": ["Lexend"],
        "button": ["Lexend"],
        "label-bold": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Lexend"],
        "headline-xl": ["Lexend"],
        "body-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "button": ["16px", { "lineHeight": "1", "fontWeight": "600" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
